### ISSUE TITLE
what is the use of isSsidHiddenStr

### ISSUE THREAD

**Issue by ghost** [EspressifApp/EsptouchForAndroidForRTOS#1]
hi,
    I don't figure out the isSsidHiddenStr use for?
##     We told SSID and PWD to device, I think its maybe enough. Can anyone explain for me? thks

```
And, I checked the source code, SSID will trans to device only if isSsidHiddenStr == true.
```

**Comment by EspressifApp** [comment]
Hi Guy,

When the Router(AP)'s ssid is not hidden, we optimize the progress and make device connect to the Router more quickly. But when the Router's ssid is hidden, we have to send more data to the device. If you are still puzzled, let us discuss it further on.
